version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: quizly-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quizly
      MYSQL_USER: quizly
      MYSQL_PASSWORD: quizly
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
